AWSTemplateFormatVersion: 2010-09-09
Parameters:
  VpcId:
    Type: 'AWS::EC2::VPC::Id'
    Description: Select a VPC that allows instances to access the Internet.
  SubnetId:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: Select at least two subnets in your selected VPC.
  ECSClusterName:
    Type: 'AWS::ECS::Cluster::ClusterName'
    Description: ECS Cluster
  FileSystemId:
    Type: 'List<AWS::EFS::FileSystem>'
    Description: Select a File System ID
  SecurityGroupId:
    Type: 'List<AWS::EC2::SecurityGroup::Id'
    Description: Select a Security Group within your selected VPC.
  AeroECSTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition::Name'
    Description: Task Definition.
  AeroTargetGroupName:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup::Name'
    Description: Target Group.
Resources:
  MountTargetVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: MountTargetVPC
  MountTargetSubnetOne:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VpcId
      AvailabilityZone: us-gov-west-1a
  MountTargetSubnetTwo:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VpcId
      AvailabilityZone: us-gov-west-1b
  FileSystemResource:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      FileSystemId: !Ref FileSystemId
      FileSystemTags:
        - Key: Name
          Value: Aero-FileSystem
      BackupPolicy:
        Status: ENABLED
      Encrypted: true
  Policy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: Statement
            Effect: Allow
            Principal: '*'
            Action:
              - 'elasticfilesystem:ClientMount'
              - 'elasticfilesystem:ClientRootAccess'
              - 'elasticfilesystem:ClientWrite'
            Resource: '*'
            Condition:
              Bool:
                'aws:SecureTransport': 'false'
  AccessPoint:
    Type: 'AWS::EFS::AccessPoint'
    Properties:
      FileSystemId: !Ref FileSystemId
      PosixUser:
        Uid: '1000'
        Gid: '1000'
  ECSService:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: !Ref ECSClusterName
      DesiredCount: 1
      EnableExecuteCommand: true
      LaunchType: EC2
      TaskDefinition: !Ref AeroECSTaskDefinition
      LoadBalancers:
        - TargetGroupName: !Ref AeroTargetGroupName
          ContainerPort: 80
          ContainerName: Strapi-app
          SecurityGroups:
            - !Ref SecurityGroupId
